# Generated by Django 4.0.2 on 2022-02-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=15)),
                ('image_location', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('date_saved', models.DateTimeField()),
                ('image_title', models.CharField(max_length=14)),
                ('user_image_location', models.ImageField(upload_to='')),
            ],
        ),
    ]
