# Generated by Django 4.0.2 on 2022-02-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoy_app', '0002_alter_imagelibrary_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelibrary',
            name='image_location',
            field=models.ImageField(upload_to='media'),
        ),
    ]
