# Generated by Django 4.0.2 on 2022-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoy_app', '0003_alter_imagelibrary_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelibrary',
            name='thumbnail_image_location',
            field=models.ImageField(default='UTC', upload_to='media'),
            preserve_default=False,
        ),
    ]
