# Generated by Django 4.0.2 on 2022-02-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoy_app', '0004_imagelibrary_thumbnail_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='user_thumbnail_image_location',
            field=models.ImageField(default='mandala.jpg', upload_to=''),
        ),
    ]
